services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\SMTPMailerBundle\Controller\:
    resource: '../../Controller/'
  Tourze\SMTPMailerBundle\Command\:
    resource: '../../Command/'
  Tourze\SMTPMailerBundle\DataFixtures\:
    resource: '../../DataFixtures/'
  Tourze\SMTPMailerBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  Tourze\SMTPMailerBundle\Repository\:
    resource: '../../Repository/'
  Tourze\SMTPMailerBundle\Service\:
    resource: '../../Service/'
