services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # DataFixtures for test environment
  Tourze\SMTPMailerBundle\DataFixtures\DevFixtures:
    tags: ['doctrine.fixture.orm']

  Tourze\SMTPMailerBundle\DataFixtures\MailTaskFixtures:
    tags: ['doctrine.fixture.orm']

  Tourze\SMTPMailerBundle\DataFixtures\SMTPConfigFixtures:
    tags: ['doctrine.fixture.orm']

  Tourze\SMTPMailerBundle\DataFixtures\ProdFixtures:
    tags: ['doctrine.fixture.orm']

# Test environment configuration
parameters:
  env(MAILER_DSN): 'smtp://localhost:25'